import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { useStore } from '@/store'
import axios from 'axios'

interface SearchResult {
  title: string
  identifier: string
  thumbnail: string
  directUrl: string
}

export default function CreateRoom() {
  const { userName, setUserName } = useStore()
  const navigate = useNavigate()
  const [name, setName] = useState(userName || '')
  const [url, setUrl] = useState('')
  const [tab, setTab] = useState<'url' | 'search'>('url')
  const [query, setQuery] = useState('')
  const [results, setResults] = useState<SearchResult[]>([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  useEffect(() => { if (userName) setName(userName) }, [userName])

  const search = async () => {
    if (!query.trim()) return
    setLoading(true); setError(''); setResults([])
    try {
      const { data } = await axios.get(`/api/search?q=${encodeURIComponent(query)}`)
      setResults(data)
      if (!data.length) setError('No results found')
    } catch { setError('Search failed') }
    setLoading(false)
  }

  const extractVideo = async () => {
    if (!url.trim()) return
    setLoading(true); setError('')
    try {
      const { data } = await axios.get(`/api/extract?url=${encodeURIComponent(url)}`)
      if (data.url) {
        setUrl(data.url)
        setError('')
      }
    } catch {
      // URL might be direct — that's OK
    }
    setLoading(false)
  }

  const createRoom = () => {
    if (!name.trim()) return setError('Enter your name')
    if (!url.trim()) return setError('Paste a video URL or select from search')
    setUserName(name.trim())
    // Room ID is generated by the server when we join via socket
    // We'll use a temporary code and the WatchRoom page handles the rest
    const tempCode = Array.from({ length: 6 }, () => 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[Math.floor(Math.random() * 31)]).join('')
    localStorage.setItem('sw_pending_url', url)
    navigate(`/room/${tempCode}`)
  }

  return (
    <div className="min-h-screen bg-sw-bg">
      <nav className="flex items-center justify-between px-6 py-4 max-w-4xl mx-auto">
        <a href="/" className="text-sw-gold font-bold text-xl">SomniWatch</a>
      </nav>

      <div className="max-w-xl mx-auto px-6 pt-12">
        <h1 className="text-2xl font-bold mb-8">Create a Room</h1>

        {/* Name */}
        <label className="block text-sw-muted text-sm mb-2">Your name</label>
        <input
          className="sw-input mb-6"
          placeholder="Enter your name"
          value={name}
          onChange={e => setName(e.target.value)}
        />

        {/* Tabs */}
        <div className="flex gap-4 mb-4">
          <button
            className={`text-sm font-medium pb-1 transition ${tab === 'url' ? 'text-sw-gold border-b-2 border-sw-gold' : 'text-sw-muted'}`}
            onClick={() => setTab('url')}
          >Paste URL</button>
          <button
            className={`text-sm font-medium pb-1 transition ${tab === 'search' ? 'text-sw-gold border-b-2 border-sw-gold' : 'text-sw-muted'}`}
            onClick={() => setTab('search')}
          >Search Movies</button>
        </div>

        {tab === 'url' && (
          <div className="flex gap-2 mb-6">
            <input
              className="sw-input flex-1"
              placeholder="https://youtube.com/watch?v=..."
              value={url}
              onChange={e => setUrl(e.target.value)}
            />
            <button onClick={extractVideo} disabled={loading} className="btn-primary px-4 py-3 text-sm shrink-0">
              {loading ? '...' : 'Load'}
            </button>
          </div>
        )}

        {tab === 'search' && (
          <>
            <div className="flex gap-2 mb-4">
              <input
                className="sw-input flex-1"
                placeholder="Search archive.org movies..."
                value={query}
                onChange={e => setQuery(e.target.value)}
                onKeyDown={e => e.key === 'Enter' && search()}
              />
              <button onClick={search} disabled={loading} className="btn-primary px-4 py-3 text-sm shrink-0">
                {loading ? '...' : 'Search'}
              </button>
            </div>
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 mb-6 max-h-80 overflow-y-auto">
              {results.map(r => (
                <button
                  key={r.identifier}
                  className={`card p-2 text-left transition hover:border-sw-gold ${url === r.directUrl ? 'card-gold' : ''}`}
                  onClick={() => setUrl(r.directUrl)}
                >
                  <img src={r.thumbnail} alt={r.title} className="w-full aspect-video object-cover rounded-lg mb-2 bg-sw-surface" />
                  <p className="text-xs text-sw-text line-clamp-2">{r.title}</p>
                </button>
              ))}
            </div>
          </>
        )}

        {url && (
          <div className="card card-gold p-3 mb-6">
            <p className="text-xs text-sw-muted mb-1">Selected video</p>
            <p className="text-sm text-sw-text truncate">{url}</p>
          </div>
        )}

        {error && <p className="text-sw-red text-sm mb-4">{error}</p>}

        <button onClick={createRoom} className="btn-primary w-full py-4 text-base">
          Create Room →
        </button>
      </div>
    </div>
  )
}
